export const products = [
  {
    id: 1,
    title: 'Aero Wireless Headphones',
    description: 'Noise-reducing headphones with soft memory foam cups and 36 hour battery life.',
    price: '$129',
    icon: 'fa-headphones-simple',
    image: '/product-images/Wireless%20Headphones.png',
    category: 'Audio',
    rating: 4.8,
  },
  {
    id: 2,
    title: 'Pulse Smart Watch',
    description: 'A slim health tracker with sleep insights, workout modes, and message previews.',
    price: '$89',
    icon: 'fa-clock',
    image: '/product-images/Smart%20Watch.png',
    category: 'Wearable',
    rating: 4.6,
  },
  {
    id: 3,
    title: 'Orbit Desk Lamp',
    description: 'Adjustable LED task lamp with warm-to-cool lighting and touch controls.',
    price: '$54',
    icon: 'fa-lightbulb',
    image: '/product-images/lamp.png',
    category: 'Workspace',
    rating: 4.4,
  },
  {
    id: 4,
    title: 'Nova Travel Pack',
    description: 'Weather-resistant everyday backpack with padded laptop storage and organizers.',
    price: '$76',
    icon: 'fa-bag-shopping',
    image: '/product-images/Bag.png',
    category: 'Travel',
    rating: 4.7,
  },
  {
    id: 5,
    title: 'Mini Bluetooth Speaker',
    description: 'Portable speaker with balanced bass, splash resistance, and instant pairing.',
    price: '$48',
    icon: 'fa-volume-high',
    image: '/product-images/Bluetooth%20Speaker.png',
    category: 'Audio',
    rating: 4.5,
  },
  {
    id: 6,
    title: 'Pixel Compact Camera',
    description: 'Lightweight travel camera with sharp autofocus and vivid color capture.',
    price: '$215',
    icon: 'fa-camera',
    image: '/product-images/Camera.png',
    category: 'Camera',
    rating: 4.9,
  },
  {
    id: 7,
    title: 'Studio Monitor Headset',
    description: 'Closed-back headset tuned for calls, focus sessions, and clean audio playback.',
    price: '$142',
    icon: 'fa-headset',
    image: '/product-images/headphones.png',
    category: 'Audio',
    rating: 4.7,
  },
  {
    id: 8,
    title: 'TrackFit Sport Watch',
    description: 'Durable fitness watch with GPS tracking, heart metrics, and quick charging.',
    price: '$118',
    icon: 'fa-person-running',
    image: '/product-images/watch.png',
    category: 'Fitness',
    rating: 4.5,
  },
  {
    id: 9,
    title: 'Glow Reading Lamp',
    description: 'Compact lamp with low-glare light modes for desks, shelves, and bedside tables.',
    price: '$39',
    icon: 'fa-sun',
    image: '/product-images/white%20lamp.png',
    category: 'Workspace',
    rating: 4.3,
  },
  {
    id: 10,
    title: 'Metro Work Backpack',
    description: 'Structured laptop bag with bottle pocket, cable loops, and secure front storage.',
    price: '$92',
    icon: 'fa-briefcase',
    image: '/product-images/backpack.png',
    category: 'Travel',
    rating: 4.6,
  },
  {
    id: 11,
    title: 'RoomFill Smart Speaker',
    description: 'Voice-ready home speaker with rich room audio and a clean fabric finish.',
    price: '$99',
    icon: 'fa-podcast',
    image: '/product-images/Speaker.png',
    category: 'Audio',
    rating: 4.4,
  },
  {
    id: 12,
    title: 'Creator Vlog Camera',
    description: 'Pocket camera for creators with flip preview, fast capture, and steady video.',
    price: '$249',
    icon: 'fa-video',
    image: '/product-images/Camera1.png',
    category: 'Camera',
    rating: 4.8,
  },
];

export const topProducts = [
  { name: 'Creator Vlog Camera', orders: 42, revenue: '$10,458' },
  { name: 'Pixel Compact Camera', orders: 38, revenue: '$8,170' },
  { name: 'Aero Wireless Headphones', orders: 35, revenue: '$4,515' },
  { name: 'TrackFit Sport Watch', orders: 31, revenue: '$3,658' },
];

export const productOrders = [
  ['ORD-1001', 'Aero Wireless Headphones', 'Audio', '2 items', '$258'],
  ['ORD-1002', 'Creator Vlog Camera', 'Camera', '1 item', '$249'],
  ['ORD-1003', 'Metro Work Backpack', 'Travel', '3 items', '$276'],
  ['ORD-1004', 'Pulse Smart Watch', 'Wearable', '2 items', '$178'],
  ['ORD-1005', 'Mini Bluetooth Speaker', 'Audio', '4 items', '$192'],
  ['ORD-1006', 'Glow Reading Lamp', 'Workspace', '2 items', '$78'],
];
